# Generated by Django 2.2 on 2021-01-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.IntegerField()),
                ('corp_hq', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='employers.Employer')),
            ],
        ),
    ]
