# Generated by Django 2.2 on 2021-01-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='1', max_length=150),
            preserve_default=False,
        ),
    ]
