# Generated by Django 2.2 on 2021-01-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hired_applicant', to='applicants.Applicant'),
        ),
    ]
